"""initial

Revision ID: da311443c8b6
Revises: 
Create Date: 2026-05-10 22:36:57.120206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da311443c8b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: autogenerated revision attempted to drop PostGIS system
    # tables (`spatial_ref_sys`) and an application table `cities`.
    # Dropping PostGIS internal tables breaks the database; remove those
    # operations so migration only applies app schema changes.
    op.add_column('fortresses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('fortresses', sa.Column('architectural_style', sa.String(), nullable=True))
    op.alter_column('fortresses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('fortresses', 'image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('fortresses', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('fortresses', 'wikipedia_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('fortresses', 'wikidata_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_fortresses_wikidata_id'), table_name='fortresses')
    op.create_index('idx_fortresses_location', 'fortresses', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_fortresses_id'), 'fortresses', ['id'], unique=False)
    op.create_index(op.f('ix_fortresses_name'), 'fortresses', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fortresses_name'), table_name='fortresses')
    op.drop_index(op.f('ix_fortresses_id'), table_name='fortresses')
    op.drop_index('idx_fortresses_location', table_name='fortresses', postgresql_using='gist')
    op.create_index(op.f('idx_fortresses_wikidata_id'), 'fortresses', ['wikidata_id'], unique=False)
    op.alter_column('fortresses', 'wikidata_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fortresses', 'wikipedia_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fortresses', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fortresses', 'image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('fortresses', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('fortresses', 'architectural_style')
    op.drop_column('fortresses', 'description')
    # Removed creation of PostGIS internal table `spatial_ref_sys` and
    # auxiliary `cities` table which were added by autogeneration but
    # should not be managed by this revision. These objects are
    # typically provided by the database (PostGIS extension) or by a
    # separate controlled migration.
    # ### end Alembic commands ###
